sudo: false
cache: bundler
bundler_args: --no-deployment
branches:
  only: master
script: bundle exec rake $TASK
env:
  matrix:
    - TASK='db:create db:migrate default'
    - TASK=brakeman
    - TASK=bundle_audit

